version: '3'
networks: 
  stack: {}

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.3
    volumes:
      - "./data/logstash/:/usr/share/logstash/logs/"
      - "./pipeline/:/usr/share/logstash/pipeline/"
      - "./logs/:/var/log/"
    networks:
      - stack
    depends_on:
      - elasticsearch
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    ports:
       - "9200:9200"
       - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./data/elasticsearch/:/usr/share/elasticsearch/data/"
    networks:
      - stack
    deploy:
      resources:
        limits:
          memory: 1G
  
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"
    volumes:
      - "./data/kibana/:/usr/share/kibana/data/"
    networks:
      - stack
    depends_on:
      - elasticsearch